### ISSUE TITLE
missing image images/foto.jpg

### ISSUE THREAD

**Issue by aubi** [evamarko/j2w-ukol01#1]
The source uses [image tag](https://github.com/evamarko/j2w-ukol01/blob/7035577ff1f58bcd5e36ae4176505f44e0eb1075/src/main/resources/static/index.html#L16)
```
<img src="images/foto.jpg" ...
```
But the image is not part of the project.

**Comment by evamarko** [comment]
Thanks a lot for the feedback. I have added the image to the project.
